service: ssmac
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1
  memorySize: 128
functions:
  hello-world:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
